version: "3"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
    - 9393:9300
    volumes:
    - ./inputFile:/csvserver/inputdata
    env_file:
    - ./csvserver.env

  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - csvserver
